### Init data
GET http://localhost:8080/admin/data

### Add order
POST http://localhost:8080/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 3,
      "quantity": 10
    },
    {
      "bookId": 4,
      "quantity": 1
    }
  ],
  "recipient": {
    "name": "John Doe",
    "phone": "123-456-789",
    "street": "Cwiartki 3/4",
    "city": "Krakow",
    "zipCode": "30-150",
    "email": "johndoe@example.org"
  }
}

### Get order by id
GET http://localhost:8080/orders/9

###
PUT http://localhost:8080/orders/5/status
Content-Type: application/json

{
  "status" : "CANCELED"
}